spring.application.name=Midnight-Blog

# DATASOURCE
spring.datasource.url=jdbc:postgresql://localhost:5492/midnight_database
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=${POSTGRES_USER:MIDNIGHT_ADMIN}
spring.datasource.password=${POSTGRES_PASSWORD:MIDNIGHT_DEV_PASSWORD}

# JPA
spring.jpa.properties.hibernate.default_schema=public
spring.jpa.open-in-view=true
spring.jpa.hibernate.ddl-auto=update